language: node_js
node_js:
- '8'
script:
- echo 'Build starts!!'
- echo 'Installing Deps!'
- yarn
- echo 'Building'
- webpack
addons:
  ssh_known_hosts: turizsolt.hu
before_install:
- openssl aes-256-cbc -K $encrypted_5591823c49dc_key -iv $encrypted_5591823c49dc_iv
  -in deploy_rsa.enc -out ./deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- ssh-add ./deploy_rsa
- ssh -i ./deploy_rsa git@turizsolt.hu ./deploy_fahrplan.sh

